---
- name: Create VPC
  amazon.aws.ec2_vpc_net:
    name: "{{ project_name }}-{{ env }}"
    cidr_block: "{{ vpc_cidr }}"
    tags:
      Name: "{{ project_name }}-{{ env }}-vpc"
      Environment: "{{ env }}"
  register: vpc

- name: Create Internet Gateway
  amazon.aws.ec2_vpc_igw:
    vpc_id: "{{ vpc.vpc.id }}"
    state: present
    tags:
      Name: "{{ project_name }}-{{ env }}-igw"
      Environment: "{{ env }}"
  register: igw

- name: Create Public Subnet
  amazon.aws.ec2_vpc_subnet:
    vpc_id: "{{ vpc.vpc.id }}"
    cidr: "{{ public_subnet_cidr }}"
    az: "{{ lookup('env','AWS_DEFAULT_REGION') | default('us-east-1', true) }}a"
    map_public: true
    tags:
      Name: "{{ project_name }}-{{ env }}-public-1a"
      Environment: "{{ env }}"
  register: public_subnet

- name: Create Public Route Table
  amazon.aws.ec2_vpc_route_table:
    vpc_id: "{{ vpc.vpc.id }}"
    tags:
      Name: "{{ project_name }}-{{ env }}-public-rt"
      Environment: "{{ env }}"
    subnets:
      - "{{ public_subnet.subnet.id }}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ igw.gateway_id }}"

