---
- name: Destroy environment
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    env: "{{ env | default('dev') }}"
  tasks:
    - name: Find EC2 instances by tag
      amazon.aws.ec2_instance_info:
        filters:
          "tag:Environment": "{{ env }}"
      register: ec2_info

    - name: Terminate EC2
      amazon.aws.ec2_instance:
        instance_ids: "{{ ec2_info.instances | map(attribute='instance_id') | list }}"
        state: absent
      when: ec2_info.instances | length > 0

    - name: (Optionally) remove security group, route table, subnets, VPC
      debug:
        msg: "Implement teardown of SG, routes, subnets, VPC if required"

